### ISSUE TITLE
tomotools reconstruct file and folder structure

### ISSUE THREAD

**Issue by McHaillet** [tomotools/tomotools#25]
Hi again,

The following line is failing for me:
https://github.com/tomotools/tomotools/blob/a3c9a3583bc70cd45a370302cf71108969d3fc29/tomotools/utils/tiltseries.py#L307

This is the error message:
```
Traceback (most recent call last):
  File "/data2/mchaillet/programs/tomotools/env/bin/tomotools", line 8, in <module>
    sys.exit(tomotools())
  File "/data2/mchaillet/programs/tomotools/env/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data2/mchaillet/programs/tomotools/env/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data2/mchaillet/programs/tomotools/env/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data2/mchaillet/programs/tomotools/env/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data2/mchaillet/programs/tomotools/env/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data2/mchaillet/programs/tomotools/env/lib/python3.8/site-packages/tomotools/commands/preprocessing_reconstruction.py", line 500, in reconstruct
    tiltseries_ali = align_with_areTomo(
  File "/data2/mchaillet/programs/tomotools/env/lib/python3.8/site-packages/tomotools/utils/tiltseries.py", line 307, in align_with_areTomo
    aln_to_tlt(aln_file)
  File "/data2/mchaillet/programs/tomotools/env/lib/python3.8/site-packages/tomotools/utils/tiltseries.py", line 515, in aln_to_tlt
    with open(aln_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'stacks/01122021_BrnoKrios_arctis_lam1_pos4.aln'
```

My input stack is called stacks/01122021_BrnoKrios_arctis_lam1_pos4.st, and the aln file generated by aretomo is called stacks/01122021_BrnoKrios_arctis_lam1_pos4.st.aln. So tomotools did not set the align file correctly here (https://github.com/tomotools/tomotools/blob/a3c9a3583bc70cd45a370302cf71108969d3fc29/tomotools/utils/tiltseries.py#L243). It should rather append `.aln` to the `ts.path`. 

Perhaps there is a difference in AreTomo version? FYI, I am running 1.3.4

Also, I am currently calling `tomotools reconstruct` with e.g. `stacks/tomo_id.st` as input file, where stacks has the following structure:
```
+- stacks/
¦  +- tomo_id.st
¦  +- tomo_id.st.mdoc
¦  +- tomo_id.tlt
```
Is this correct? 

Best wishes,
Marten

**Comment by bwmr** [comment]
Fixed [here](https://github.com/tomotools/tomotools/commit/f3d094ba0fbc97077bbf5c915d44f3558e6c26a6)

Again, thanks for raising the issue :)
